version: '3'

services:
  nginx-proxy:
    image: priyal0810/nginxact1:latest
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment:
      - FLASK_SERVER_ADDR=flask-app:5000
    ports:
      - "80:80"
    depends_on:
      - flask-app
    # Uncomment the healthcheck if needed
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    command: [ "sh", "/start.sh" ]

  flask-app:
    image: priyal0810/flaskact1:latest
    restart: always
    ports:
      - '5000:5000'
    # Uncomment the healthcheck if needed
    # healthcheck:
    #   test: ["CMD-SHELL", "curl --silent --fail localhost:5000/flask-health-check || exit 1"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]

